# Generated by Django 6.0.5 on 2026-05-21 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0003_funcionario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('problema', models.TextField()),
                ('solucao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='relatorios/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='funcionarios.funcionario')),
            ],
        ),
    ]
