# Generated by Django 6.0.5 on 2026-05-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='resultado_final',
            field=models.TextField(blank=True, null=True),
        ),
    ]
