# Generated by Django 6.0.5 on 2026-05-26 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_foto'),
        ('relatorios', '0003_relatorio_palavras_chave_relatorio_prioridade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='relatorios.relatorio')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='relatorios.relatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
            options={
                'unique_together': {('relatorio', 'usuario')},
            },
        ),
    ]
