# Generated by Django 6.0.5 on 2026-06-01 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_foto'),
        ('relatorios', '0004_comentario_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('util', 'Útil'), ('nao_ajudou', 'Não ajudou')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='relatorios.relatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
            options={
                'unique_together': {('relatorio', 'usuario')},
            },
        ),
    ]
