# Generated by Django 6.0.5 on 2026-06-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0005_curtida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='relatorio',
            name='tags',
            field=models.ManyToManyField(blank=True, to='relatorios.tag'),
        ),
    ]
