# Generated by Django 6.0.5 on 2026-06-03 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_foto'),
        ('relatorios', '0006_tag_relatorio_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('problema', models.TextField()),
                ('solucao', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='relatorios.relatorio')),
            ],
        ),
    ]
