# Generated by Django 6.0.6 on 2026-06-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_foto'),
        ('relatorios', '0008_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
    ]
